apiVersion: v1
kind: Service
metadata:
  name: bank-user
  labels:
    app.kubernetes.io/name: bank-user
    app.kubernetes.io/part-of: my-bank
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bank-user
  ports:
    - name: http
      port: 80
      targetPort: http
