apiVersion: v1
kind: Service
metadata:
  name: core-banking
  labels:
    app.kubernetes.io/name: core-banking
    app.kubernetes.io/part-of: my-bank
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: core-banking
  ports:
    - name: http
      port: 80
      targetPort: http
