apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-bank
  labels:
    app.kubernetes.io/part-of: my-bank
  annotations:
    # Uncomment for cert-manager TLS
    # cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: core-api.dental-care.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: core-banking
                port:
                  name: http
    - host: users-api.dental-care.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bank-user
                port:
                  name: http
  # tls:
  #   - hosts:
  #       - core-api.dental-care.me
  #       - users-api.dental-care.me
  #     secretName: my-bank-tls
