apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-bank

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: my-bank

resources:
  - namespace.yaml
  - postgres/configmap-init.yaml
  - postgres/secret.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - core-banking/secret.yaml
  - core-banking/deployment.yaml
  - core-banking/service.yaml
  - bank-user/secret.yaml
  - bank-user/deployment.yaml
  - bank-user/service.yaml
  - c-user/secret.yaml
  - c-user/deployment.yaml
  - c-user/service.yaml
  - bank-dashboard/configmap.yaml
  - bank-dashboard/deployment.yaml
  - bank-dashboard/service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/example/my-bank/core-banking
    newName: ghcr.io/example/my-bank/core-banking
    newTag: latest
  - name: ghcr.io/example/my-bank/bank-user
    newName: ghcr.io/example/my-bank/bank-user
    newTag: latest
  - name: ghcr.io/example/my-bank/c-user
    newName: ghcr.io/example/my-bank/c-user
    newTag: latest
  - name: ghcr.io/example/my-bank/bank-dashboard
    newName: ghcr.io/example/my-bank/bank-dashboard
    newTag: latest
